# Generated by Django 4.0.5 on 2022-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_status', models.CharField(max_length=100)),
                ('align', models.CharField(max_length=100)),
                ('eye', models.CharField(max_length=100)),
                ('hair', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('gsm', models.CharField(max_length=100)),
                ('alive', models.BooleanField(default=True)),
                ('appearances', models.IntegerField()),
                ('first_appearance', models.TextField()),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=10)),
            ],
        ),
    ]
